version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    labels:
      - chore
      - update
    assignees:
      - LexisNexis-RBA/iog-systemsengineering
