apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    aadpodidbinding: {{ .Values.azureIdentity.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        aadpodidbinding: {{ .Values.azureIdentity.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image }}"
          command: ["/bin/bash", "/startup.sh"]
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          volumeMounts:
            - name: scripts
              mountPath: /startup.sh
              subPath: startup
      volumes:
        - name: scripts
          configMap:
            name: scripts
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | trim | indent 8 }}
{{- end }}
      tolerations:
{{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | indent 8  }}
{{- end }}