blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/LexisNexis-RBA/rsg-kubernetes/discussions
    about: If you're asking a question or aren't sure if you have an issue please use the RSG Kubernetes GitHub Discussions.
