apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.dns_name }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: {{ .Values.name }}
  selector:
    app: {{ .Values.name }}