apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lnrs-k8s-api
  labels:
    lnrs.io/monitoring-platform: core-prometheus
  namespace: monitoring
spec:
  groups:
    - name: lnrs-k8s-api.rules
      rules:
        - alert: KubeVersionMismatch
          expr: count(count by (gitVersion) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"gitVersion","$1","gitVersion","(v[0-9]*.[0-9]*).*"))) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes version mismatch"
            description: "There are {{ $value }} different semantic versions of Kubernetes components running.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeClientErrors
          expr: (sum(rate(rest_client_requests_total{code=~"5.."}[5m])) by (instance, job) / sum(rate(rest_client_requests_total[5m])) by (instance, job)) > 0.01
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes client errors"
            description: "Kubernetes API server client {{ $labels.job }}/{{ $labels.instance }} is experiencing {{ $value | humanizePercentage }} errors.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeClientCertificateExpiration
          expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 604800
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes client certificate expiration"
            description: "A client certificate used to authenticate to the apiserver is expiring in less than 7 days.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeClientCertificateExpiration
          expr: apiserver_client_certificate_expiration_seconds_count{job="apiserver"} > 0 and on(job) histogram_quantile(0.01, sum by (job, le) (rate(apiserver_client_certificate_expiration_seconds_bucket{job="apiserver"}[5m]))) < 86400
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes client certificate expiration"
            description: "A client certificate used to authenticate to the apiserver is expiring in less than 24 hours.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: AggregatedAPIErrors
          expr: sum by(name, namespace)(increase(aggregator_unavailable_apiservice_count[5m])) > 2
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes aggregated api errors"
            description: "An aggregated API {{ $labels.name }}/{{ $labels.namespace }} has reported errors. The number of errors have increased for it in the past five minutes. High values indicate that the availability of the service changes too often.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: AggregatedAPIDown
          expr: (1 - max by(name, namespace)(avg_over_time(aggregator_unavailable_apiservice[5m]))) < 0.9
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes aggregated api down"
            description: "An aggregated API {{ $labels.name }}/{{ $labels.namespace }} has been only {{ $value | humanize }}% available over the last 5m.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeAPIDown
          expr: absent(up{job="apiserver"} == 1)
          for: 15m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes api down"
            description: "KubeAPI has disappeared from Prometheus target discovery.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
