apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lnrs-k8s-cluster
  labels:
    lnrs.io/monitoring-platform: core-prometheus
  namespace: monitoring
spec:
  groups:
    - name: lnrs-k8s-cluster.rules
      rules:
        - alert: KubeCPUOvercommit
          expr: sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum) / sum(kube_node_status_allocatable_cpu_cores) > (count(kube_node_status_allocatable_cpu_cores) - 1) / count(kube_node_status_allocatable_cpu_cores)
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes cluster CPU overcommit"
            description: "Kubernetes cluster has overcommitted CPU resource requests for pods and cannot tolerate node failure.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeMemoryOvercommit
          expr: sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum) / sum(kube_node_status_allocatable_memory_bytes) > (count(kube_node_status_allocatable_memory_bytes) - 1) / count(kube_node_status_allocatable_memory_bytes)
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes cluster memory overcommit"
            description: "Kubernetes cluster has overcommitted memory resource requests for pods and cannot tolerate node failure.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeCPUQuotaOvercommit
          expr: sum(kube_resourcequota{resource="cpu",type="hard"}) / sum(kube_node_status_allocatable_cpu_cores) > 1.5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes cluster CPU quota overcommit"
            description: "Kubernetes cluster has overcommitted CPU resource requests for namespaces.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubeMemoryQuotaOvercommit
          expr: sum(kube_resourcequota{resource="memory",type="hard"}) / sum(kube_node_status_allocatable_memory_bytes) > 1.5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes cluster memory quota overcommit"
            description: "Kubernetes cluster has overcommitted memory resource requests for namespaces.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
