apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lnrs-k8s-container
  labels:
    lnrs.io/monitoring-platform: core-prometheus
  namespace: monitoring
spec:
  groups:
    - name: lnrs-k8s-container.rules
      rules:
        - alert: KubernetesContainerCPUThrottling
          expr: sum by(container, pod, namespace) (increase(container_cpu_cfs_throttled_periods_total{container!="POD", container!="", image!=""}[5m])) / sum by(container, pod, namespace) (increase (container_cpu_cfs_periods_total[5m])) > 0.25
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes container CPU throttling"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} and namespace {{ $labels.namespace}} is seeing {{ $value | humanizePercentage }} throttling of CPU.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubernetesContainerMemoryOverLimit
          expr: sum(container_memory_working_set_bytes{container!="POD", container!="", image!=""}) by (container, pod, namespace) / sum(label_join(kube_pod_container_resource_limits_memory_bytes, "container", "", "container")) by (container, pod, namespace) > 1
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes container memory over limit"
            description: "Container {{ $labels.container }} in pod {{ $labels.pod }} and namespace {{ $labels.namespace}} is seeing {{ $value | humanizePercentage }} usage of memeory limt.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

        - alert: KubernetesContainerOOMKilled
          expr:
            sum(max by(namespace, container, pod) (increase(kube_pod_container_status_restarts_total[12m])) and max by(namespace, container, pod) (kube_pod_container_status_last_terminated_reason{reason="OOMKilled"})
            == 1) > 5
          for: 15m
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes container OOM killed"
            description: "Multiple containers were out of memory killed within the past 15 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
