apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lnrs-fluent-bit
  labels:
    lnrs.io/monitoring-platform: core-prometheus
  namespace: monitoring
spec:
  groups:
    - name: lnrs-fluent-bit.rules
      rules:
        - alert: FluentbitNoOutputBytesProcessed
          expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Fluent Bit no output bytes processed"
            descritpion: "Output plugin {{ $labels.name }} on Pod {{ $labels.namespace }}/{{ $labels.pod }} has not processed any bytes for at least 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"