apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: lnrs-fluentd
  labels:
    lnrs.io/monitoring-platform: core-prometheus
  namespace: monitoring
spec:
  groups:
    - name: lnrs-fluentd.rules
      rules:
        - alert: FluentdOutputStatusRetry
          expr: increase(fluentd_output_status_retry_count[5m]) > 2
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Fluentd output status retry"
            descritpion: "Output plugin {{ $labels.type }} on Pod {{ $labels.namespace }}/{{ $labels.instance }} has been retrying over the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - alert: FluentdOutputBufferQueueLength
          expr: max_over_time(fluentd_status_buffer_queue_length[5m]) > 2
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Fluentd output buffer queue length"
            descritpion: "Output plugin {{ $labels.type }} on Pod {{ $labels.namespace }}/{{ $labels.instance }} has a buffer that can not been flushed.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"