name: Stale Issues
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Stale Issues
        uses: actions/stale@1160a2240286f5da8ec72b1c0816ce2481aabf84 # v8.0.0
        with:
          repo-token: ${{ secrets.SECRET }}
          days-before-stale: 14
          stale-issue-label: Stale
          stale-issue-message: |
            This issue has been marked as stale because it has been inactive for 14 days.
            If you believe this issue is still relevant, please provide an update. Otherwise, it may be closed in the future.
          remove-issue-stale-when-updated: true
          enable-statistics: true
          operations-per-run: 150
          ascending: false
          days-before-close: -1
          debug-only: true # dry run
