name: Validate

on:
  workflow_dispatch:

jobs:
  workflow:
    name: Reusable Workflow
    uses: LexisNexis-RBA/rsg-terraform-workflows/.github/workflows/module-validate.yaml@main
    secrets: inherit
    with:
      module_name: terraform-azurerm-aks
      terraform_version: 1.3.3
