name: Validate

on:
  workflow_dispatch:

jobs:
  workflow:
    name: Reusable Workflow
    uses: LexisNexis-RBA/rsg-gh-workflows-terraform/.github/workflows/module-validate.yaml@main
    secrets: inherit
    with:
      module_name: terraform-azurerm-aks
