apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lnrs:cluster-view
  labels:
    lnrs.io/k8s-platform : "true"
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
  - watch
