apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lnrs:aggregate-to-view
  labels:
    lnrs.io/k8s-platform: "true"
    lnrs.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - ""
  resources:
  - node
  verbs:
  - get
  - list
  - watch
